###############################################对象（map）,键值对的集合数据格式##########################
user1:
  name: xiaoming
  age: 12

user2: {name: xiaoming,age: 12}  #行内写法


##############################################数组格式####################################################
likes1:
  - running
  - ping-pong

likes2: [running,ping-pong]  #行内写法


##############################################纯量格式，单个的，不可再分的值#################################
msg1: 'hello \n word'  #单引号忽略转义字符,会原样输出
msg2: "hello \n word"  #双引号识别转义字符，会将 \n 转换为换行，输出两行



############################################参数引用格式######################################################
password: 123456

user3:
  name: xiaoming
  password: ${password}  #引用上面定义的password值